services:
  - type: web
    name: carelink-bharat-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://care-link-bharat.vercel.app
      - key: COOKIE_DOMAIN
        value: onrender.com
      - key: MONGODB_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://carelink-bharat-api.onrender.com/api/v1/auth/google/callback
